<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="wwwroot\app.html" />
    <None Remove="wwwroot\home.css" />
    <None Remove="wwwroot\home.html" />
    <None Remove="wwwroot\index.html" />
    <None Remove="wwwroot\landing.css" />
    <None Remove="wwwroot\login.css" />
    <None Remove="wwwroot\login.html" />
    <None Remove="wwwroot\settings.css" />
    <None Remove="wwwroot\settings.html" />
    <None Remove="wwwroot\settings.js" />
    <None Remove="wwwroot\style.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
    <Content Include="wwwroot\home.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\home.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\landing.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\login.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\login.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\settings.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\settings.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\settings.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\style.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Web.WebView2" Version="1.0.3595.46" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\data\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\app.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>